
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snowText`=list(
        `type`="software", 
        `author`="Seol, H.", 
        `year`=2026, 
        `title`="snowText: Text Mining Analysis", 
        `publisher`="(Version 1.0) [jamovi module]. URL https://github.com/hyunsooseol/snowText", 
        `url`="https://github.com/hyunsooseol/snowText"))
