
# This file is automatically generated, you probably don't want to edit this

klexiconOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "klexiconOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            textVar = NULL,
            lexicon = list(
                list(category="\uAE0D\uC815 \uC815\uC11C", terms="\uC88B*, \uB9CC\uC871*, \uD589\uBCF5*, \uAE30\uC058*, \uCD94\uCC9C*"),
                list(category="\uBD80\uC815 \uC815\uC11C", terms="\uB098\uC058*, \uC2E4\uB9DD*, \uBD88\uB9CC*, \uBD88\uD3B8*, \uC2EB*"),
                list(category="\uBD88\uC548", terms="\uBD88\uC548*, \uAC71\uC815*, \uB450\uB835*, \uAE34\uC7A5*, \uCD08\uC870*"),
                list(category="\uC131\uCDE8", terms="\uC131\uACF5*, \uC131\uCDE8*, \uB2EC\uC131*, \uD5A5\uC0C1*, \uBC1C\uC804*")),
            normalizeKorean = TRUE,
            negationMode = "exclude",
            negationWindow = 1,
            negationCues = "\uC54A*, \uBABB*, \uC548",
            documentDetails = FALSE,
            negationEvidence = FALSE,
            categoryPlot = FALSE,
            negationImpactPlot = FALSE,
            cooccurrence = FALSE,
            cooccurrencePlot = FALSE,
            prevalencePlot = FALSE, ...) {

            super$initialize(
                package="snowText",
                name="klexicon",
                requiresData=TRUE,
                ...)

            private$..textVar <- jmvcore::OptionVariable$new(
                "textVar",
                textVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "id",
                    "factor"))
            private$..lexicon <- jmvcore::OptionArray$new(
                "lexicon",
                lexicon,
                default=list(
                    list(category="\uAE0D\uC815 \uC815\uC11C", terms="\uC88B*, \uB9CC\uC871*, \uD589\uBCF5*, \uAE30\uC058*, \uCD94\uCC9C*"),
                    list(category="\uBD80\uC815 \uC815\uC11C", terms="\uB098\uC058*, \uC2E4\uB9DD*, \uBD88\uB9CC*, \uBD88\uD3B8*, \uC2EB*"),
                    list(category="\uBD88\uC548", terms="\uBD88\uC548*, \uAC71\uC815*, \uB450\uB835*, \uAE34\uC7A5*, \uCD08\uC870*"),
                    list(category="\uC131\uCDE8", terms="\uC131\uACF5*, \uC131\uCDE8*, \uB2EC\uC131*, \uD5A5\uC0C1*, \uBC1C\uC804*")),
                template=jmvcore::OptionGroup$new(
                    "lexicon",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "category",
                            NULL),
                        jmvcore::OptionString$new(
                            "terms",
                            NULL))))
            private$..normalizeKorean <- jmvcore::OptionBool$new(
                "normalizeKorean",
                normalizeKorean,
                default=TRUE)
            private$..negationMode <- jmvcore::OptionList$new(
                "negationMode",
                negationMode,
                options=list(
                    "none",
                    "flag",
                    "exclude"),
                default="exclude")
            private$..negationWindow <- jmvcore::OptionInteger$new(
                "negationWindow",
                negationWindow,
                min=1,
                max=5,
                default=1)
            private$..negationCues <- jmvcore::OptionString$new(
                "negationCues",
                negationCues,
                default="\uC54A*, \uBABB*, \uC548")
            private$..documentDetails <- jmvcore::OptionBool$new(
                "documentDetails",
                documentDetails,
                default=FALSE)
            private$..negationEvidence <- jmvcore::OptionBool$new(
                "negationEvidence",
                negationEvidence,
                default=FALSE)
            private$..saveResults <- jmvcore::OptionOutput$new(
                "saveResults")
            private$..detectedWords <- jmvcore::OptionOutput$new(
                "detectedWords")
            private$..categoryPlot <- jmvcore::OptionBool$new(
                "categoryPlot",
                categoryPlot,
                default=FALSE)
            private$..negationImpactPlot <- jmvcore::OptionBool$new(
                "negationImpactPlot",
                negationImpactPlot,
                default=FALSE)
            private$..cooccurrence <- jmvcore::OptionBool$new(
                "cooccurrence",
                cooccurrence,
                default=FALSE)
            private$..cooccurrencePlot <- jmvcore::OptionBool$new(
                "cooccurrencePlot",
                cooccurrencePlot,
                default=FALSE)
            private$..prevalencePlot <- jmvcore::OptionBool$new(
                "prevalencePlot",
                prevalencePlot,
                default=FALSE)

            self$.addOption(private$..textVar)
            self$.addOption(private$..lexicon)
            self$.addOption(private$..normalizeKorean)
            self$.addOption(private$..negationMode)
            self$.addOption(private$..negationWindow)
            self$.addOption(private$..negationCues)
            self$.addOption(private$..documentDetails)
            self$.addOption(private$..negationEvidence)
            self$.addOption(private$..saveResults)
            self$.addOption(private$..detectedWords)
            self$.addOption(private$..categoryPlot)
            self$.addOption(private$..negationImpactPlot)
            self$.addOption(private$..cooccurrence)
            self$.addOption(private$..cooccurrencePlot)
            self$.addOption(private$..prevalencePlot)
        }),
    active = list(
        textVar = function() private$..textVar$value,
        lexicon = function() private$..lexicon$value,
        normalizeKorean = function() private$..normalizeKorean$value,
        negationMode = function() private$..negationMode$value,
        negationWindow = function() private$..negationWindow$value,
        negationCues = function() private$..negationCues$value,
        documentDetails = function() private$..documentDetails$value,
        negationEvidence = function() private$..negationEvidence$value,
        saveResults = function() private$..saveResults$value,
        detectedWords = function() private$..detectedWords$value,
        categoryPlot = function() private$..categoryPlot$value,
        negationImpactPlot = function() private$..negationImpactPlot$value,
        cooccurrence = function() private$..cooccurrence$value,
        cooccurrencePlot = function() private$..cooccurrencePlot$value,
        prevalencePlot = function() private$..prevalencePlot$value),
    private = list(
        ..textVar = NA,
        ..lexicon = NA,
        ..normalizeKorean = NA,
        ..negationMode = NA,
        ..negationWindow = NA,
        ..negationCues = NA,
        ..documentDetails = NA,
        ..negationEvidence = NA,
        ..saveResults = NA,
        ..detectedWords = NA,
        ..categoryPlot = NA,
        ..negationImpactPlot = NA,
        ..cooccurrence = NA,
        ..cooccurrencePlot = NA,
        ..prevalencePlot = NA)
)

klexiconResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "klexiconResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        dictSummary = function() private$.items[["dictSummary"]],
        matchingSummary = function() private$.items[["matchingSummary"]],
        catSummary = function() private$.items[["catSummary"]],
        documentDetails = function() private$.items[["documentDetails"]],
        negationEvidence = function() private$.items[["negationEvidence"]],
        cooccurrence = function() private$.items[["cooccurrence"]],
        statusNote = function() private$.items[["statusNote"]],
        categoryPlot = function() private$.items[["categoryPlot"]],
        negationImpactPlot = function() private$.items[["negationImpactPlot"]],
        cooccurrencePlot = function() private$.items[["cooccurrencePlot"]],
        prevalencePlot = function() private$.items[["prevalencePlot"]],
        saveResults = function() private$.items[["saveResults"]],
        detectedWords = function() private$.items[["detectedWords"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Korean Lexicon Analysis",
                refs="snowText")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="dictSummary",
                title="Dictionary Summary",
                rows=0,
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="exactTerms", 
                        `title`="Exact Terms", 
                        `type`="integer"),
                    list(
                        `name`="wildcardPrefixes", 
                        `title`="Wildcard Prefixes", 
                        `type`="integer"),
                    list(
                        `name`="multiWordTerms", 
                        `title`="Multi-word Terms", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="matchingSummary",
                title="Korean Matching Settings",
                rows=0,
                clearWith=list(
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues"),
                columns=list(
                    list(
                        `name`="setting", 
                        `title`="Setting", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="catSummary",
                title="Category Counts Summary",
                rows=0,
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="rawCount", 
                        `title`="Raw Matches", 
                        `type`="integer"),
                    list(
                        `name`="negatedCount", 
                        `title`="Negated Matches", 
                        `type`="integer"),
                    list(
                        `name`="adjustedCount", 
                        `title`="Adjusted Matches", 
                        `type`="integer"),
                    list(
                        `name`="meanCount", 
                        `title`="Mean / Doc", 
                        `type`="number"),
                    list(
                        `name`="meanPerc", 
                        `title`="Mean Token Proportion", 
                        `type`="number"),
                    list(
                        `name`="docCount", 
                        `title`="Docs with Matches", 
                        `type`="integer"),
                    list(
                        `name`="docPerc", 
                        `title`="% of Docs", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="documentDetails",
                title="Matching Document Details",
                rows=0,
                visible="(documentDetails)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues"),
                columns=list(
                    list(
                        `name`="document", 
                        `title`="Document", 
                        `type`="integer"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="tokens", 
                        `title`="Tokens", 
                        `type`="integer"),
                    list(
                        `name`="rawCount", 
                        `title`="Raw Matches", 
                        `type`="integer"),
                    list(
                        `name`="adjustedCount", 
                        `title`="Adjusted Matches", 
                        `type`="integer"),
                    list(
                        `name`="percentage", 
                        `title`="Token Proportion", 
                        `type`="number"),
                    list(
                        `name`="detectedTerms", 
                        `title`="Raw Detected Terms", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="negationEvidence",
                title="Negation Evidence",
                rows=0,
                visible="(negationEvidence)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues"),
                columns=list(
                    list(
                        `name`="document", 
                        `title`="Document", 
                        `type`="integer"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="matchedTerm", 
                        `title`="Matched Term", 
                        `type`="text"),
                    list(
                        `name`="negationCue", 
                        `title`="Negation Cue", 
                        `type`="text"),
                    list(
                        `name`="context", 
                        `title`="Context", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Treatment", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cooccurrence",
                title="Category Co-occurrence",
                rows=0,
                visible="(cooccurrence)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues",
                    "cooccurrence"),
                columns=list(
                    list(
                        `name`="category1", 
                        `title`="Category 1", 
                        `type`="text"),
                    list(
                        `name`="category2", 
                        `title`="Category 2", 
                        `type`="text"),
                    list(
                        `name`="docCount", 
                        `title`="Docs with Both", 
                        `type`="integer"),
                    list(
                        `name`="docPerc", 
                        `title`="% of Docs", 
                        `type`="number"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="statusNote",
                title="Status",
                visible=FALSE,
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues")))
            self$add(jmvcore::Image$new(
                options=options,
                name="categoryPlot",
                title="Category Match Plot",
                width=650,
                height=450,
                renderFun=".plotCategoryMatches",
                visible="(categoryPlot)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues")))
            self$add(jmvcore::Image$new(
                options=options,
                name="negationImpactPlot",
                title="Negation Impact Plot",
                width=650,
                height=450,
                renderFun=".plotNegationImpact",
                visible="(negationImpactPlot)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues")))
            self$add(jmvcore::Image$new(
                options=options,
                name="cooccurrencePlot",
                title="Category Co-occurrence Heatmap",
                width=650,
                height=550,
                renderFun=".plotCategoryCooccurrence",
                visible="(cooccurrencePlot)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues",
                    "cooccurrencePlot")))
            self$add(jmvcore::Image$new(
                options=options,
                name="prevalencePlot",
                title="Category Prevalence Plot",
                width=650,
                height=450,
                renderFun=".plotCategoryPrevalence",
                visible="(prevalencePlot)",
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues",
                    "prevalencePlot")))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveResults",
                title="Analysis scores",
                initInRun=TRUE,
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues",
                    "detectedWords")))
            self$add(jmvcore::Output$new(
                options=options,
                name="detectedWords",
                title="Detected terms",
                initInRun=TRUE,
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "normalizeKorean",
                    "negationMode",
                    "negationWindow",
                    "negationCues",
                    "detectedWords")))}))

klexiconBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "klexiconBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowText",
                name = "klexicon",
                version = c(1,0,0),
                options = options,
                results = klexiconResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Korean Lexicon Analysis
#'
#' Performs dictionary-based text analysis with Korean-oriented matching 
#' rules. User-defined categories support exact terms, prefix wildcards, and 
#' multi-word expressions. Optional Korean negation handling identifies and 
#' adjusts lexicon matches occurring with nearby negation cues.
#' @param data .
#' @param textVar .
#' @param lexicon Four example categories are provided by default. Users may
#'   freely edit, remove, or add categories. Enter terms as a comma-separated
#'   list. A trailing * indicates prefix matching. Multi-word expressions are
#'   allowed.
#' @param normalizeKorean .
#' @param negationMode .
#' @param negationWindow .
#' @param negationCues Enter Korean negation cues as a comma-separated list. A
#'   trailing * indicates prefix matching.
#' @param documentDetails .
#' @param negationEvidence .
#' @param categoryPlot .
#' @param negationImpactPlot .
#' @param cooccurrence Counts documents in which both categories have at least
#'   one adjusted match.
#' @param cooccurrencePlot .
#' @param prevalencePlot Displays the percentage of documents with at least
#'   one adjusted match in each category.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$dictSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$matchingSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$catSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$documentDetails} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$negationEvidence} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cooccurrence} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$statusNote} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$categoryPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$negationImpactPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cooccurrencePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$prevalencePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$saveResults} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$detectedWords} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dictSummary$asDF}
#'
#' \code{as.data.frame(results$dictSummary)}
#'
#' @export
klexicon <- function(
    data,
    textVar,
    lexicon = list(
                list(category="\uAE0D\uC815 \uC815\uC11C", terms="\uC88B*, \uB9CC\uC871*, \uD589\uBCF5*, \uAE30\uC058*, \uCD94\uCC9C*"),
                list(category="\uBD80\uC815 \uC815\uC11C", terms="\uB098\uC058*, \uC2E4\uB9DD*, \uBD88\uB9CC*, \uBD88\uD3B8*, \uC2EB*"),
                list(category="\uBD88\uC548", terms="\uBD88\uC548*, \uAC71\uC815*, \uB450\uB835*, \uAE34\uC7A5*, \uCD08\uC870*"),
                list(category="\uC131\uCDE8", terms="\uC131\uACF5*, \uC131\uCDE8*, \uB2EC\uC131*, \uD5A5\uC0C1*, \uBC1C\uC804*")),
    normalizeKorean = TRUE,
    negationMode = "exclude",
    negationWindow = 1,
    negationCues = "\uC54A*, \uBABB*, \uC548",
    documentDetails = FALSE,
    negationEvidence = FALSE,
    categoryPlot = FALSE,
    negationImpactPlot = FALSE,
    cooccurrence = FALSE,
    cooccurrencePlot = FALSE,
    prevalencePlot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("klexicon requires jmvcore to be installed (restart may be required)")

    if ( ! missing(textVar)) textVar <- jmvcore::resolveQuo(jmvcore::enquo(textVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(textVar), textVar, NULL))


    options <- klexiconOptions$new(
        textVar = textVar,
        lexicon = lexicon,
        normalizeKorean = normalizeKorean,
        negationMode = negationMode,
        negationWindow = negationWindow,
        negationCues = negationCues,
        documentDetails = documentDetails,
        negationEvidence = negationEvidence,
        categoryPlot = categoryPlot,
        negationImpactPlot = negationImpactPlot,
        cooccurrence = cooccurrence,
        cooccurrencePlot = cooccurrencePlot,
        prevalencePlot = prevalencePlot)

    analysis <- klexiconClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

