
# This file is automatically generated, you probably don't want to edit this

lexicalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lexicalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            words = NULL,
            freq = NULL,
            vocabularyStructure = TRUE,
            concentration = FALSE,
            coverage = FALSE,
            zipf = FALSE,
            rankFrequencyPlot = FALSE,
            lorenzPlot = FALSE,
            frequencySpectrumPlot = FALSE,
            vocabularyConcentrationPlot = FALSE, ...) {

            super$initialize(
                package="snowText",
                name="lexical",
                requiresData=TRUE,
                ...)

            private$..words <- jmvcore::OptionVariable$new(
                "words",
                words,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..freq <- jmvcore::OptionVariable$new(
                "freq",
                freq,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..vocabularyStructure <- jmvcore::OptionBool$new(
                "vocabularyStructure",
                vocabularyStructure,
                default=TRUE)
            private$..concentration <- jmvcore::OptionBool$new(
                "concentration",
                concentration,
                default=FALSE)
            private$..coverage <- jmvcore::OptionBool$new(
                "coverage",
                coverage,
                default=FALSE)
            private$..zipf <- jmvcore::OptionBool$new(
                "zipf",
                zipf,
                default=FALSE)
            private$..rankFrequencyPlot <- jmvcore::OptionBool$new(
                "rankFrequencyPlot",
                rankFrequencyPlot,
                default=FALSE)
            private$..lorenzPlot <- jmvcore::OptionBool$new(
                "lorenzPlot",
                lorenzPlot,
                default=FALSE)
            private$..frequencySpectrumPlot <- jmvcore::OptionBool$new(
                "frequencySpectrumPlot",
                frequencySpectrumPlot,
                default=FALSE)
            private$..vocabularyConcentrationPlot <- jmvcore::OptionBool$new(
                "vocabularyConcentrationPlot",
                vocabularyConcentrationPlot,
                default=FALSE)

            self$.addOption(private$..words)
            self$.addOption(private$..freq)
            self$.addOption(private$..vocabularyStructure)
            self$.addOption(private$..concentration)
            self$.addOption(private$..coverage)
            self$.addOption(private$..zipf)
            self$.addOption(private$..rankFrequencyPlot)
            self$.addOption(private$..lorenzPlot)
            self$.addOption(private$..frequencySpectrumPlot)
            self$.addOption(private$..vocabularyConcentrationPlot)
        }),
    active = list(
        words = function() private$..words$value,
        freq = function() private$..freq$value,
        vocabularyStructure = function() private$..vocabularyStructure$value,
        concentration = function() private$..concentration$value,
        coverage = function() private$..coverage$value,
        zipf = function() private$..zipf$value,
        rankFrequencyPlot = function() private$..rankFrequencyPlot$value,
        lorenzPlot = function() private$..lorenzPlot$value,
        frequencySpectrumPlot = function() private$..frequencySpectrumPlot$value,
        vocabularyConcentrationPlot = function() private$..vocabularyConcentrationPlot$value),
    private = list(
        ..words = NA,
        ..freq = NA,
        ..vocabularyStructure = NA,
        ..concentration = NA,
        ..coverage = NA,
        ..zipf = NA,
        ..rankFrequencyPlot = NA,
        ..lorenzPlot = NA,
        ..frequencySpectrumPlot = NA,
        ..vocabularyConcentrationPlot = NA)
)

lexicalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lexicalResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        vocabularyStructure = function() private$.items[["vocabularyStructure"]],
        concentration = function() private$.items[["concentration"]],
        coverage = function() private$.items[["coverage"]],
        zipf = function() private$.items[["zipf"]],
        rankFrequencyPlot = function() private$.items[["rankFrequencyPlot"]],
        lorenzPlot = function() private$.items[["lorenzPlot"]],
        frequencySpectrumPlot = function() private$.items[["frequencySpectrumPlot"]],
        vocabularyConcentrationPlot = function() private$.items[["vocabularyConcentrationPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Lexical Distribution",
                refs="snowText")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="vocabularyStructure",
                title="Vocabulary Structure",
                visible="(vocabularyStructure)",
                clearWith=list(
                    "words",
                    "freq"),
                columns=list(
                    list(
                        `name`="vocabularySize", 
                        `title`="Vocabulary Size", 
                        `type`="integer"),
                    list(
                        `name`="totalTokens", 
                        `title`="Total Tokens", 
                        `type`="integer"),
                    list(
                        `name`="hapaxCount", 
                        `title`="Hapax", 
                        `type`="integer"),
                    list(
                        `name`="hapaxRatio", 
                        `title`="Hapax Ratio", 
                        `type`="number"),
                    list(
                        `name`="disCount", 
                        `title`="Dis Legomena", 
                        `type`="integer"),
                    list(
                        `name`="disRatio", 
                        `title`="Dis Ratio", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="concentration",
                title="Distribution Concentration",
                visible="(concentration)",
                clearWith=list(
                    "words",
                    "freq"),
                columns=list(
                    list(
                        `name`="shannon", 
                        `title`="Shannon H", 
                        `type`="number"),
                    list(
                        `name`="normalizedEntropy", 
                        `title`="Normalized Entropy", 
                        `type`="number"),
                    list(
                        `name`="gini", 
                        `title`="Gini", 
                        `type`="number"),
                    list(
                        `name`="simpson", 
                        `title`="Simpson Concentration", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coverage",
                title="Coverage Analysis",
                visible="(coverage)",
                clearWith=list(
                    "words",
                    "freq"),
                columns=list(
                    list(
                        `name`="top10", 
                        `title`="Top 10 Coverage (%)", 
                        `type`="number"),
                    list(
                        `name`="top20", 
                        `title`="Top 20 Coverage (%)", 
                        `type`="number"),
                    list(
                        `name`="coverage50", 
                        `title`="Words for 50%", 
                        `type`="integer"),
                    list(
                        `name`="coverage80", 
                        `title`="Words for 80%", 
                        `type`="integer"),
                    list(
                        `name`="coverage90", 
                        `title`="Words for 90%", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="zipf",
                title="Zipf Diagnostics",
                visible="(zipf)",
                clearWith=list(
                    "words",
                    "freq"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="Words", 
                        `type`="integer"),
                    list(
                        `name`="slope", 
                        `title`="Slope", 
                        `type`="number"),
                    list(
                        `name`="intercept", 
                        `title`="Intercept", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="rankFrequencyPlot",
                title="Rank-Frequency Plot",
                width=650,
                height=450,
                renderFun=".plotRankFrequency",
                visible="(rankFrequencyPlot)",
                clearWith=list(
                    "words",
                    "freq")))
            self$add(jmvcore::Image$new(
                options=options,
                name="lorenzPlot",
                title="Lorenz Curve",
                width=650,
                height=450,
                renderFun=".plotLorenz",
                visible="(lorenzPlot)",
                clearWith=list(
                    "words",
                    "freq")))
            self$add(jmvcore::Image$new(
                options=options,
                name="frequencySpectrumPlot",
                title="Frequency Spectrum",
                width=650,
                height=450,
                renderFun=".plotFrequencySpectrum",
                visible="(frequencySpectrumPlot)",
                clearWith=list(
                    "words",
                    "freq")))
            self$add(jmvcore::Image$new(
                options=options,
                name="vocabularyConcentrationPlot",
                title="Vocabulary Concentration Map",
                width=650,
                height=450,
                renderFun=".plotVocabularyConcentration",
                visible="(vocabularyConcentrationPlot)",
                clearWith=list(
                    "words",
                    "freq")))}))

lexicalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lexicalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowText",
                name = "lexical",
                version = c(1,0,0),
                options = options,
                results = lexicalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Lexical Distribution
#'
#' 
#' @param data .
#' @param words .
#' @param freq .
#' @param vocabularyStructure .
#' @param concentration .
#' @param coverage .
#' @param zipf .
#' @param rankFrequencyPlot .
#' @param lorenzPlot .
#' @param frequencySpectrumPlot .
#' @param vocabularyConcentrationPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$vocabularyStructure} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$concentration} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coverage} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$zipf} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$rankFrequencyPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$lorenzPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$frequencySpectrumPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$vocabularyConcentrationPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$vocabularyStructure$asDF}
#'
#' \code{as.data.frame(results$vocabularyStructure)}
#'
#' @export
lexical <- function(
    data,
    words,
    freq,
    vocabularyStructure = TRUE,
    concentration = FALSE,
    coverage = FALSE,
    zipf = FALSE,
    rankFrequencyPlot = FALSE,
    lorenzPlot = FALSE,
    frequencySpectrumPlot = FALSE,
    vocabularyConcentrationPlot = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lexical requires jmvcore to be installed (restart may be required)")

    if ( ! missing(words)) words <- jmvcore::resolveQuo(jmvcore::enquo(words))
    if ( ! missing(freq)) freq <- jmvcore::resolveQuo(jmvcore::enquo(freq))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(words), words, NULL),
            `if`( ! missing(freq), freq, NULL))

    for (v in words) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lexicalOptions$new(
        words = words,
        freq = freq,
        vocabularyStructure = vocabularyStructure,
        concentration = concentration,
        coverage = coverage,
        zipf = zipf,
        rankFrequencyPlot = rankFrequencyPlot,
        lorenzPlot = lorenzPlot,
        frequencySpectrumPlot = frequencySpectrumPlot,
        vocabularyConcentrationPlot = vocabularyConcentrationPlot)

    analysis <- lexicalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

