
# This file is automatically generated, you probably don't want to edit this

lexicalComparisonOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lexicalComparisonOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            words = NULL,
            freq = NULL,
            group = NULL,
            distributionDifference = TRUE,
            vocabularyOverlap = FALSE,
            concentrationDifference = FALSE,
            contribution = FALSE,
            distancePlot = FALSE,
            contributionPlot = FALSE,
            angle = 0, ...) {

            super$initialize(
                package="snowText",
                name="lexicalComparison",
                requiresData=TRUE,
                ...)

            private$..words <- jmvcore::OptionVariable$new(
                "words",
                words,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..freq <- jmvcore::OptionVariable$new(
                "freq",
                freq,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..distributionDifference <- jmvcore::OptionBool$new(
                "distributionDifference",
                distributionDifference,
                default=TRUE)
            private$..vocabularyOverlap <- jmvcore::OptionBool$new(
                "vocabularyOverlap",
                vocabularyOverlap,
                default=FALSE)
            private$..concentrationDifference <- jmvcore::OptionBool$new(
                "concentrationDifference",
                concentrationDifference,
                default=FALSE)
            private$..contribution <- jmvcore::OptionBool$new(
                "contribution",
                contribution,
                default=FALSE)
            private$..distancePlot <- jmvcore::OptionBool$new(
                "distancePlot",
                distancePlot,
                default=FALSE)
            private$..contributionPlot <- jmvcore::OptionBool$new(
                "contributionPlot",
                contributionPlot,
                default=FALSE)
            private$..angle <- jmvcore::OptionNumber$new(
                "angle",
                angle,
                min=0,
                max=90,
                default=0)

            self$.addOption(private$..words)
            self$.addOption(private$..freq)
            self$.addOption(private$..group)
            self$.addOption(private$..distributionDifference)
            self$.addOption(private$..vocabularyOverlap)
            self$.addOption(private$..concentrationDifference)
            self$.addOption(private$..contribution)
            self$.addOption(private$..distancePlot)
            self$.addOption(private$..contributionPlot)
            self$.addOption(private$..angle)
        }),
    active = list(
        words = function() private$..words$value,
        freq = function() private$..freq$value,
        group = function() private$..group$value,
        distributionDifference = function() private$..distributionDifference$value,
        vocabularyOverlap = function() private$..vocabularyOverlap$value,
        concentrationDifference = function() private$..concentrationDifference$value,
        contribution = function() private$..contribution$value,
        distancePlot = function() private$..distancePlot$value,
        contributionPlot = function() private$..contributionPlot$value,
        angle = function() private$..angle$value),
    private = list(
        ..words = NA,
        ..freq = NA,
        ..group = NA,
        ..distributionDifference = NA,
        ..vocabularyOverlap = NA,
        ..concentrationDifference = NA,
        ..contribution = NA,
        ..distancePlot = NA,
        ..contributionPlot = NA,
        ..angle = NA)
)

lexicalComparisonResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lexicalComparisonResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        distributionDifference = function() private$.items[["distributionDifference"]],
        vocabularyOverlap = function() private$.items[["vocabularyOverlap"]],
        concentrationDifference = function() private$.items[["concentrationDifference"]],
        contribution = function() private$.items[["contribution"]],
        distancePlot = function() private$.items[["distancePlot"]],
        contributionPlot = function() private$.items[["contributionPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Lexical Distribution Comparison",
                refs="snowText")
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="Instructions",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="distributionDifference",
                title="Distribution Difference",
                visible="(distributionDifference)",
                clearWith=list(
                    "words",
                    "freq",
                    "group"),
                columns=list(
                    list(
                        `name`="group1", 
                        `title`="Group 1", 
                        `type`="text"),
                    list(
                        `name`="group2", 
                        `title`="Group 2", 
                        `type`="text"),
                    list(
                        `name`="jsd", 
                        `title`="Jensen-Shannon", 
                        `type`="number"),
                    list(
                        `name`="hellinger", 
                        `title`="Hellinger", 
                        `type`="number"),
                    list(
                        `name`="brayCurtis", 
                        `title`="Bray-Curtis", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="vocabularyOverlap",
                title="Vocabulary Overlap",
                visible="(vocabularyOverlap)",
                clearWith=list(
                    "words",
                    "freq",
                    "group"),
                columns=list(
                    list(
                        `name`="group1", 
                        `title`="Group 1", 
                        `type`="text"),
                    list(
                        `name`="group2", 
                        `title`="Group 2", 
                        `type`="text"),
                    list(
                        `name`="vocabulary1", 
                        `title`="Vocabulary 1", 
                        `type`="integer"),
                    list(
                        `name`="vocabulary2", 
                        `title`="Vocabulary 2", 
                        `type`="integer"),
                    list(
                        `name`="sharedWords", 
                        `title`="Shared Words", 
                        `type`="integer"),
                    list(
                        `name`="unionWords", 
                        `title`="Union Words", 
                        `type`="integer"),
                    list(
                        `name`="jaccard", 
                        `title`="Jaccard Similarity", 
                        `type`="number"),
                    list(
                        `name`="sharedPct", 
                        `title`="Shared Vocabulary (%)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="concentrationDifference",
                title="Concentration Difference",
                visible="(concentrationDifference)",
                clearWith=list(
                    "words",
                    "freq",
                    "group"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="vocabulary", 
                        `title`="Vocabulary Size", 
                        `type`="integer"),
                    list(
                        `name`="tokens", 
                        `title`="Total Tokens", 
                        `type`="integer"),
                    list(
                        `name`="entropy", 
                        `title`="Shannon H", 
                        `type`="number"),
                    list(
                        `name`="normalizedEntropy", 
                        `title`="Normalized Entropy", 
                        `type`="number"),
                    list(
                        `name`="gini", 
                        `title`="Gini", 
                        `type`="number"),
                    list(
                        `name`="simpson", 
                        `title`="Simpson Concentration", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="contribution",
                title="Difference Breakdown",
                visible="(contribution)",
                clearWith=list(
                    "words",
                    "freq",
                    "group"),
                columns=list(
                    list(
                        `name`="group1", 
                        `title`="Group 1", 
                        `type`="text"),
                    list(
                        `name`="group2", 
                        `title`="Group 2", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Word Category", 
                        `type`="text"),
                    list(
                        `name`="wordCount", 
                        `title`="Words", 
                        `type`="integer"),
                    list(
                        `name`="jsContribution", 
                        `title`="JS Contribution", 
                        `type`="number"),
                    list(
                        `name`="contributionPct", 
                        `title`="Share of JS (%)", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="distancePlot",
                title="Distribution Distance Plot",
                width=650,
                height=450,
                renderFun=".plotDistance",
                visible="(distancePlot)",
                clearWith=list(
                    "words",
                    "freq",
                    "group")))
            self$add(jmvcore::Image$new(
                options=options,
                name="contributionPlot",
                title="Contribution Plot",
                width=650,
                height=450,
                renderFun=".plotContribution",
                visible="(contributionPlot)",
                clearWith=list(
                    "words",
                    "freq",
                    "group",
                    "angle")))}))

lexicalComparisonBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "lexicalComparisonBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowText",
                name = "lexicalComparison",
                version = c(1,0,0),
                options = options,
                results = lexicalComparisonResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Lexical Distribution Comparison
#'
#' 
#' @param data .
#' @param words .
#' @param freq .
#' @param group .
#' @param distributionDifference .
#' @param vocabularyOverlap .
#' @param concentrationDifference .
#' @param contribution .
#' @param distancePlot .
#' @param contributionPlot .
#' @param angle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$distributionDifference} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$vocabularyOverlap} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$concentrationDifference} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$contribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$distancePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$contributionPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$distributionDifference$asDF}
#'
#' \code{as.data.frame(results$distributionDifference)}
#'
#' @export
lexicalComparison <- function(
    data,
    words,
    freq,
    group,
    distributionDifference = TRUE,
    vocabularyOverlap = FALSE,
    concentrationDifference = FALSE,
    contribution = FALSE,
    distancePlot = FALSE,
    contributionPlot = FALSE,
    angle = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("lexicalComparison requires jmvcore to be installed (restart may be required)")

    if ( ! missing(words)) words <- jmvcore::resolveQuo(jmvcore::enquo(words))
    if ( ! missing(freq)) freq <- jmvcore::resolveQuo(jmvcore::enquo(freq))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(words), words, NULL),
            `if`( ! missing(freq), freq, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in words) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- lexicalComparisonOptions$new(
        words = words,
        freq = freq,
        group = group,
        distributionDifference = distributionDifference,
        vocabularyOverlap = vocabularyOverlap,
        concentrationDifference = concentrationDifference,
        contribution = contribution,
        distancePlot = distancePlot,
        contributionPlot = contributionPlot,
        angle = angle)

    analysis <- lexicalComparisonClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

