
# This file is automatically generated, you probably don't want to edit this

profileOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "profileOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            lengthVar = NULL,
            group = NULL,
            idVar = NULL,
            lengthBias = TRUE,
            multivariate = FALSE,
            outliers = FALSE,
            redundancy = FALSE,
            dataQuality = FALSE,
            adjustedRelationships = FALSE, ...) {

            super$initialize(
                package="snowText",
                name="profile",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..lengthVar <- jmvcore::OptionVariable$new(
                "lengthVar",
                lengthVar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..idVar <- jmvcore::OptionVariable$new(
                "idVar",
                idVar,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..lengthBias <- jmvcore::OptionBool$new(
                "lengthBias",
                lengthBias,
                default=TRUE)
            private$..multivariate <- jmvcore::OptionBool$new(
                "multivariate",
                multivariate,
                default=FALSE)
            private$..outliers <- jmvcore::OptionBool$new(
                "outliers",
                outliers,
                default=FALSE)
            private$..redundancy <- jmvcore::OptionBool$new(
                "redundancy",
                redundancy,
                default=FALSE)
            private$..dataQuality <- jmvcore::OptionBool$new(
                "dataQuality",
                dataQuality,
                default=FALSE)
            private$..adjustedRelationships <- jmvcore::OptionBool$new(
                "adjustedRelationships",
                adjustedRelationships,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..lengthVar)
            self$.addOption(private$..group)
            self$.addOption(private$..idVar)
            self$.addOption(private$..lengthBias)
            self$.addOption(private$..multivariate)
            self$.addOption(private$..outliers)
            self$.addOption(private$..redundancy)
            self$.addOption(private$..dataQuality)
            self$.addOption(private$..adjustedRelationships)
        }),
    active = list(
        vars = function() private$..vars$value,
        lengthVar = function() private$..lengthVar$value,
        group = function() private$..group$value,
        idVar = function() private$..idVar$value,
        lengthBias = function() private$..lengthBias$value,
        multivariate = function() private$..multivariate$value,
        outliers = function() private$..outliers$value,
        redundancy = function() private$..redundancy$value,
        dataQuality = function() private$..dataQuality$value,
        adjustedRelationships = function() private$..adjustedRelationships$value),
    private = list(
        ..vars = NA,
        ..lengthVar = NA,
        ..group = NA,
        ..idVar = NA,
        ..lengthBias = NA,
        ..multivariate = NA,
        ..outliers = NA,
        ..redundancy = NA,
        ..dataQuality = NA,
        ..adjustedRelationships = NA)
)

profileResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "profileResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        lengthBias = function() private$.items[["lengthBias"]],
        multivariateTest = function() private$.items[["multivariateTest"]],
        profileContribution = function() private$.items[["profileContribution"]],
        outliers = function() private$.items[["outliers"]],
        redundancy = function() private$.items[["redundancy"]],
        dataQuality = function() private$.items[["dataQuality"]],
        dataQualitySummary = function() private$.items[["dataQualitySummary"]],
        adjustedRelationships = function() private$.items[["adjustedRelationships"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Text Profile",
                refs="snowText")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Text Profile"))
            self$add(jmvcore::Table$new(
                options=options,
                name="lengthBias",
                title="Length Bias Diagnostics",
                rows="(vars)",
                visible="(lengthBias)",
                clearWith=list(
                    "vars",
                    "lengthVar"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Measure", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="correlation", 
                        `title`="Length r", 
                        `type`="number"),
                    list(
                        `name`="slope", 
                        `title`="Slope", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="R\u00B2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effect", 
                        `title`="Length Effect", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="multivariateTest",
                title="Multivariate Profile Test",
                visible="(multivariate)",
                clearWith=list(
                    "vars",
                    "group"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number"),
                    list(
                        `name`="approxF", 
                        `title`="Approx. F", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="profileContribution",
                title="Contribution to Profile Difference",
                visible="(multivariate)",
                clearWith=list(
                    "vars",
                    "group"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="f", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="partialEta2", 
                        `title`="Partial \u03B7\u00B2", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="outliers",
                title="Profile Outliers",
                visible="(outliers)",
                clearWith=list(
                    "vars",
                    "idVar"),
                columns=list(
                    list(
                        `name`="document", 
                        `title`="Document", 
                        `type`="text"),
                    list(
                        `name`="row", 
                        `title`="Row", 
                        `type`="integer"),
                    list(
                        `name`="distance", 
                        `title`="Mahalanobis D\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="flag", 
                        `title`="Status", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="redundancy",
                title="Profile Redundancy",
                rows="(vars)",
                visible="(redundancy)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Measure", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="strongest", 
                        `title`="Strongest Association", 
                        `type`="text"),
                    list(
                        `name`="maxCorrelation", 
                        `title`="Max |r|", 
                        `type`="number"),
                    list(
                        `name`="vif", 
                        `title`="VIF", 
                        `type`="number"),
                    list(
                        `name`="status", 
                        `title`="Redundancy", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dataQuality",
                title="Profile Data Quality",
                rows="(vars)",
                visible="(dataQuality)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Measure", 
                        `type`="text", 
                        `content`="($key)"),
                    list(
                        `name`="validN", 
                        `title`="Valid N", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `title`="Missing", 
                        `type`="integer"),
                    list(
                        `name`="missingPct", 
                        `title`="Missing %", 
                        `type`="number"),
                    list(
                        `name`="unique", 
                        `title`="Unique", 
                        `type`="integer"),
                    list(
                        `name`="variance", 
                        `title`="Variance", 
                        `type`="number"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dataQualitySummary",
                title="Profile Completeness",
                visible="(dataQuality)",
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="totalN", 
                        `title`="Total Rows", 
                        `type`="integer"),
                    list(
                        `name`="completeN", 
                        `title`="Complete Rows", 
                        `type`="integer"),
                    list(
                        `name`="completePct", 
                        `title`="Complete %", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="adjustedRelationships",
                title="Length-Adjusted Relationships",
                visible="(adjustedRelationships)",
                clearWith=list(
                    "vars",
                    "lengthVar"),
                columns=list(
                    list(
                        `name`="variable1", 
                        `title`="Measure 1", 
                        `type`="text"),
                    list(
                        `name`="variable2", 
                        `title`="Measure 2", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="correlation", 
                        `title`="Partial r", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

profileBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "profileBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "snowText",
                name = "profile",
                version = c(1,0,0),
                options = options,
                results = profileResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Text Profile
#'
#' 
#' @param data .
#' @param vars .
#' @param lengthVar .
#' @param group .
#' @param idVar .
#' @param lengthBias .
#' @param multivariate .
#' @param outliers .
#' @param redundancy .
#' @param dataQuality .
#' @param adjustedRelationships .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$lengthBias} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multivariateTest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$profileContribution} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$outliers} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$redundancy} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dataQuality} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dataQualitySummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adjustedRelationships} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$lengthBias$asDF}
#'
#' \code{as.data.frame(results$lengthBias)}
#'
#' @export
profile <- function(
    data,
    vars,
    lengthVar,
    group,
    idVar,
    lengthBias = TRUE,
    multivariate = FALSE,
    outliers = FALSE,
    redundancy = FALSE,
    dataQuality = FALSE,
    adjustedRelationships = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("profile requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(lengthVar)) lengthVar <- jmvcore::resolveQuo(jmvcore::enquo(lengthVar))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(idVar)) idVar <- jmvcore::resolveQuo(jmvcore::enquo(idVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(lengthVar), lengthVar, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(idVar), idVar, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in idVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- profileOptions$new(
        vars = vars,
        lengthVar = lengthVar,
        group = group,
        idVar = idVar,
        lengthBias = lengthBias,
        multivariate = multivariate,
        outliers = outliers,
        redundancy = redundancy,
        dataQuality = dataQuality,
        adjustedRelationships = adjustedRelationships)

    analysis <- profileClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

